from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from database import Base, engine
from models.inference_result import InferenceResult
from routes import user_routes, admin_routes, image_routes, iot_routes
from contextlib import asynccontextmanager
from config import ensure_directories

# -------------------- Create Tables --------------------
Base.metadata.create_all(bind=engine)

# -------------------- Infrastructure Setup --------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup tasks
    ensure_directories()
    yield
    # Shutdown tasks (if any)

app = FastAPI(
    title="Sealant Monitoring Backend",
    description="Backend API with PWA support, IoT hooks, and background task offloading.",
    version="2.0.0",
    lifespan=lifespan
)

# -------------------- CORS Setup --------------------
origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins + ["null"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -------------------- Security Headers --------------------
@app.middleware("http")
async def add_security_headers(request, call_next):
    response = await call_next(request)
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    return response

# -------------------- Include Routers --------------------
app.include_router(user_routes.router)
app.include_router(admin_routes.router)
app.include_router(image_routes.router)
app.include_router(iot_routes.router)

# -------------------- Root --------------------
@app.get("/", summary="Root Endpoint")
async def root():
    return {"message": "Welcome to the FastAPI MVC Backend!"}

# -------------------- AI Supervisor Insights --------------------
from fastapi import Query, Depends
from sqlalchemy.orm import Session
from database import get_db
from models.model_registry import SystemObservation

@app.get("/api/system-observations", tags=["AI Supervisor"])
async def get_system_observations(
    limit: int = 50,
    offset: int = 0,
    severity: str = None,
    category: str = None,
    db: Session = Depends(get_db)
):
    """
    Retrieve logs and insights generated by the Agentic Supervisor.
    """
    query = db.query(SystemObservation)
    if severity:
        query = query.filter(SystemObservation.severity == severity.upper())
    if category:
        query = query.filter(SystemObservation.category == category.upper())
    
    total = query.count()
    observations = query.order_by(SystemObservation.created_at.desc()).offset(offset).limit(limit).all()
    
    return {
        "total": total,
        "observations": observations
    }

@app.get("/api/agent/status", tags=["AI Supervisor"])
async def get_agent_status():
    """Diagnostic endpoint for the Agentic Supervisor state."""
    return {"status": "active", "mode": "autonomous", "last_check": "See system observations"}

# -------------------- Background Supervisor --------------------
import asyncio
from agents.model_agent import get_current_model_status
from database import SessionLocal

async def autonomous_supervisor_loop():
    """
    Background loop that triggers the agent to check for system drift/anomalies every hour.
    """
    while True:
        await asyncio.sleep(3600) # Check every hour
        print("--- [AUTONOMOUS SUPERVISOR] Periodic Health Check Starting ---")
        db = SessionLocal()
        try:
            prompt = (
                "AUTONOMOUS TASK: Perform a system health check. "
                "1. Analyze recent quality metrics. "
                "2. Perform RCA if NG rate is high. "
                "3. Check for model drift. "
                "4. Log any findings as a 'System Observation'."
            )
            get_current_model_status(db, prompt=prompt, thread_id="autonomous_monitor")
        except Exception as e:
            print(f"--- [AUTONOMOUS SUPERVISOR] Error: {str(e)} ---")
        finally:
            db.close()

@app.on_event("startup")
async def startup_event():
    asyncio.create_task(autonomous_supervisor_loop())
